# -*- coding: utf-8 -*-
"""Carscan_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BSBftLi5-uvBBrb02wxsVym7ZqQ-P-W9
"""

import numpy as np
import cv2
from matplotlib import pyplot as plt
from google.colab.patches import cv2_imshow
plt.rcParams.update({'font.size':22}) 
plt.rc('legend',fontsize=16)
plt.rcParams['figure.figsize']=(30,30)

from google.colab import drive
drive.mount('/content/drive')

image1=cv2.imread('/content/drive/MyDrive/Carscan/view1.jpeg')
image2=cv2.imread('/content/drive/MyDrive/Carscan/view4.jpeg')
bkgrnd=cv2.imread('/content/drive/MyDrive/Carscan/873823.jpg')

plt.figure()
plt.title('Background image')
plt.imshow(bkgrnd)

a=[image1]
for i in a:
  hh, ww = i.shape[:2]
  lower = np.array([180]*3)
  upper = np.array([255, 255, 255])

  thresh = cv2.inRange(i, lower, upper)

  kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (20,20))
  morph = cv2.morphologyEx(thresh, cv2.MORPH_CLOSE, kernel)
  mask = cv2.bitwise_not(morph)
  final_mask=cv2.bitwise_and(morph,thresh)
  final_mask2=cv2.bitwise_or(morph,thresh)
  result = cv2.bitwise_and(i, i, mask=final_mask)

  plt.figure(1)
  plt.title('Original Image')
  plt.imshow(i)
 
  plt.figure(2)
  plt.title('Foreground Image')
  plt.imshow( result)

  thresh_not1=cv2.bitwise_not(final_mask)
  bkchng=cv2.bitwise_and(bkgrnd,bkgrnd, mask=thresh_not1)

  final=cv2.bitwise_or(bkchng, result)
  plt.figure(3)
  plt.title('Image with background replacement')
  plt.imshow(final)

  thresh_not2=cv2.bitwise_not(final_mask2)
  bkchng=cv2.bitwise_and(bkgrnd,bkgrnd, mask=thresh_not2)

  final=cv2.bitwise_or(bkchng, result)
  plt.figure(4)
  plt.imshow(final)


cv2.waitKey(0)
cv2.destroyAllWindows()

"""# New Section"""

a=[image2]
for i in a:
  hh, ww = i.shape[:2]
  lower = np.array([180]*3)
  upper = np.array([255, 255, 255])

  thresh = cv2.inRange(i, lower, upper)

  kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (20,20))
  morph = cv2.morphologyEx(thresh, cv2.MORPH_CLOSE, kernel)
  mask = cv2.bitwise_not(morph)
  final_mask=cv2.bitwise_and(morph,thresh)
  final_mask2=cv2.bitwise_or(morph,thresh)
  result = cv2.bitwise_and(i, i, mask=final_mask)

  plt.figure(1)
  plt.title('Original Image')
  plt.imshow(i)
 
  plt.figure(2)
  plt.title('Foreground Image')
  plt.imshow( result)

  thresh_not1=cv2.bitwise_not(final_mask)
  bkchng=cv2.bitwise_and(bkgrnd,bkgrnd, mask=thresh_not1)

  final=cv2.bitwise_or(bkchng, result)
  plt.figure(3)
  plt.title('Image with background replacement')
  plt.imshow(final)

  thresh_not2=cv2.bitwise_not(final_mask2)
  bkchng=cv2.bitwise_and(bkgrnd,bkgrnd, mask=thresh_not2)

  final=cv2.bitwise_or(bkchng, result)
  plt.figure(4)
  plt.imshow(final)


cv2.waitKey(0)
cv2.destroyAllWindows()

